{{-- resources/views/admin/users/edit.blade.php --}}
<x-app-layout>
    <x-slot name="header"><h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">{{ __('Modifier Utilisateur :') }} {{ $user->name }} (#{{ $user->id }})</h2></x-slot>
    <div class="py-12"><div class="max-w-4xl mx-auto sm:px-6 lg:px-8"><div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg"><div class="p-6 text-gray-900 dark:text-gray-100">
        {{-- Affichage erreurs --}}
        @if ($errors->any())<div class="mb-6 bg-red-100 ..."> ... </div>@endif
        {{-- Formulaire avec action préfixée --}}
        <form method="POST" action="{{ route('admin.users.update', $user->id) }}">@csrf @method('PUT')<div class="space-y-6">
        <div><label for="name" class="block font-medium text-sm ...">{{ __('Nom Complet') }} <span class="text-red-500">*</span></label><input type="text" name="name" id="name" class="block mt-1 w-full rounded-md ..." value="{{ old('name', $user->name) }}" required autofocus>@error('name')<p class="text-sm text-red-600 ...">{{ $message }}</p>@enderror</div>
        <div><label for="email" class="block font-medium text-sm ...">{{ __('Email (Login)') }} <span class="text-red-500">*</span></label><input type="email" name="email" id="email" class="block mt-1 w-full rounded-md ..." value="{{ old('email', $user->email) }}" required>@error('email')<p class="text-sm text-red-600 ...">{{ $message }}</p>@enderror</div>
        <div><label for="role" class="block font-medium text-sm ...">{{ __('Rôle') }} <span class="text-red-500">*</span></label><select name="role" id="role" class="block mt-1 w-full rounded-md ... {{ Auth::id() === $user->id ? 'bg-gray-100 dark:bg-gray-800 cursor-not-allowed' : '' }}" required {{ Auth::id() === $user->id ? 'disabled' : '' }}>@foreach($roles as $roleOption)<option value="{{ $roleOption }}" {{ old('role', $user->role) == $roleOption ? 'selected' : '' }}>{{ ucfirst($roleOption) }}</option>@endforeach</select>@if(Auth::id() === $user->id)<input type="hidden" name="role" value="{{ $user->role }}"><p class="mt-1 text-xs text-gray-500 dark:text-gray-400">Vous ne pouvez pas modifier votre propre rôle.</p>@endif @error('role')<p class="text-sm text-red-600 ...">{{ $message }}</p>@enderror</div>
        <hr class="dark:border-gray-700 my-2"><h3 class="text-lg font-medium text-gray-900 dark:text-gray-100">Changer Mot de Passe (Optionnel)</h3><p class="mt-1 text-xs text-gray-500 dark:text-gray-400">Laissez vide pour conserver l'actuel.</p><div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div><label for="password" class="block font-medium text-sm ...">{{ __('Nouveau Mot de Passe') }}</label><input type="password" name="password" id="password" class="block mt-1 w-full rounded-md ..." autocomplete="new-password">@error('password')<p class="text-sm text-red-600 ...">{{ $message }}</p>@enderror</div>
        <div><label for="password_confirmation" class="block font-medium text-sm ...">{{ __('Confirmer Mot de Passe') }}</label><input type="password" name="password_confirmation" id="password_confirmation" class="block mt-1 w-full rounded-md ..." autocomplete="new-password"></div>
        </div></div> {{-- Fin space-y-6 --}}
        {{-- Boutons avec lien Annuler préfixé --}}
        <div class="flex items-center justify-end mt-8 border-t border-gray-200 dark:border-gray-700 pt-6"><a href="{{ route('admin.users.index') }}" class="underline text-sm text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-100 rounded-md ... mr-4">{{ __('Annuler') }}</a><button type="submit" class="inline-flex items-center px-4 py-2 bg-indigo-600 border border-transparent ...">{{ __('Mettre à Jour Utilisateur') }}</button></div>
        </form></div></div></div></div>
</x-app-layout>